---
server:
  port: 8080

spring:
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jackson:
    auto-configure: false
  kafka:
    bootstrap-servers: localhost:${KAFKA_PORT}
    consumer:
      enable-auto-commit: false
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    messaging:
      kafka:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/