name: user-service-ci

on:
  push:
    paths:
      - 'user-service/**'
  pull_request:
    paths:
      - 'user-service/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin' 

      - name: Build and test with Gradle
        run: |
          cd user-service
          gradle clean build

#      - name: Build and push Docker image
#        run: gradlew jib
#        env:
#          JIB_BASE_DOCKER_IMAGE: ${{ secrets.JIB_BASE_DOCKER_IMAGE }}
#          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
#          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
#          JIB_IMAGE_FORMAT: ${{ secrets.JIB_IMAGE_FORMAT }}
